# Generated by Django 2.1.2 on 2018-12-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Media')),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=1000)),
                ('Stock', models.CharField(max_length=100)),
                ('PrecioEntrada', models.IntegerField()),
                ('PrecioAmazon', models.IntegerField()),
                ('PrecioFinal', models.IntegerField()),
            ],
        ),
    ]
