# Generated by Django 2.1.2 on 2018-12-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='PrecioAmazon',
        ),
    ]
